//! Names of the tags EXIF defines, per IFD.

use super::Ifd;

pub(super) fn tag_name(ifd: Ifd, tag: u16) -> Option<&'static str> {
    if ifd == Ifd::Gps {
        return Some(match tag {
            0x00 => "GPSVersionID",
            0x01 => "GPSLatitudeRef",
            0x02 => "GPSLatitude",
            0x03 => "GPSLongitudeRef",
            0x04 => "GPSLongitude",
            0x05 => "GPSAltitudeRef",
            0x06 => "GPSAltitude",
            0x07 => "GPSTimeStamp",
            0x08 => "GPSSatellites",
            0x09 => "GPSStatus",
            0x0A => "GPSMeasureMode",
            0x0B => "GPSDOP",
            0x0C => "GPSSpeedRef",
            0x0D => "GPSSpeed",
            0x0E => "GPSTrackRef",
            0x0F => "GPSTrack",
            0x10 => "GPSImgDirectionRef",
            0x11 => "GPSImgDirection",
            0x12 => "GPSMapDatum",
            0x13 => "GPSDestLatitudeRef",
            0x14 => "GPSDestLatitude",
            0x15 => "GPSDestLongitudeRef",
            0x16 => "GPSDestLongitude",
            0x17 => "GPSDestBearingRef",
            0x18 => "GPSDestBearing",
            0x19 => "GPSDestDistanceRef",
            0x1A => "GPSDestDistance",
            0x1B => "GPSProcessingMethod",
            0x1C => "GPSAreaInformation",
            0x1D => "GPSDateStamp",
            0x1E => "GPSDifferential",
            0x1F => "GPSHPositioningError",
            _ => return None,
        });
    }
    if ifd == Ifd::Interop {
        return match tag {
            0x0001 => Some("InteroperabilityIndex"),
            0x0002 => Some("InteroperabilityVersion"),
            _ => None,
        };
    }
    Some(match tag {
        0x0100 => "ImageWidth",
        0x0101 => "ImageLength",
        0x0102 => "BitsPerSample",
        0x0103 => "Compression",
        0x0106 => "PhotometricInterpretation",
        0x010E => "ImageDescription",
        0x010F => "Make",
        0x0110 => "Model",
        0x0111 => "StripOffsets",
        0x0112 => "Orientation",
        0x0115 => "SamplesPerPixel",
        0x011A => "XResolution",
        0x011B => "YResolution",
        0x0128 => "ResolutionUnit",
        0x0131 => "Software",
        0x0132 => "DateTime",
        0x013B => "Artist",
        0x013E => "WhitePoint",
        0x013F => "PrimaryChromaticities",
        0x0201 => "JPEGInterchangeFormat",
        0x0202 => "JPEGInterchangeFormatLength",
        0x0211 => "YCbCrCoefficients",
        0x0213 => "YCbCrPositioning",
        0x0214 => "ReferenceBlackWhite",
        0x8298 => "Copyright",
        0x829A => "ExposureTime",
        0x829D => "FNumber",
        0x8769 => "ExifIFDPointer",
        0x8822 => "ExposureProgram",
        0x8825 => "GPSInfoIFDPointer",
        0x8827 => "ISOSpeedRatings",
        0x8830 => "SensitivityType",
        0x9000 => "ExifVersion",
        0x9003 => "DateTimeOriginal",
        0x9004 => "DateTimeDigitized",
        0x9010 => "OffsetTime",
        0x9011 => "OffsetTimeOriginal",
        0x9012 => "OffsetTimeDigitized",
        0x9101 => "ComponentsConfiguration",
        0x9102 => "CompressedBitsPerPixel",
        0x9201 => "ShutterSpeedValue",
        0x9202 => "ApertureValue",
        0x9203 => "BrightnessValue",
        0x9204 => "ExposureBiasValue",
        0x9205 => "MaxApertureValue",
        0x9206 => "SubjectDistance",
        0x9207 => "MeteringMode",
        0x9208 => "LightSource",
        0x9209 => "Flash",
        0x920A => "FocalLength",
        0x9214 => "SubjectArea",
        0x927C => "MakerNote",
        0x9286 => "UserComment",
        0x9290 => "SubSecTime",
        0x9291 => "SubSecTimeOriginal",
        0x9292 => "SubSecTimeDigitized",
        0xA000 => "FlashpixVersion",
        0xA001 => "ColorSpace",
        0xA002 => "PixelXDimension",
        0xA003 => "PixelYDimension",
        0xA004 => "RelatedSoundFile",
        0xA005 => "InteroperabilityIFDPointer",
        0xA20E => "FocalPlaneXResolution",
        0xA20F => "FocalPlaneYResolution",
        0xA210 => "FocalPlaneResolutionUnit",
        0xA217 => "SensingMethod",
        0xA300 => "FileSource",
        0xA301 => "SceneType",
        0xA401 => "CustomRendered",
        0xA402 => "ExposureMode",
        0xA403 => "WhiteBalance",
        0xA404 => "DigitalZoomRatio",
        0xA405 => "FocalLengthIn35mmFilm",
        0xA406 => "SceneCaptureType",
        0xA430 => "CameraOwnerName",
        0xA431 => "BodySerialNumber",
        0xA432 => "LensSpecification",
        0xA433 => "LensMake",
        0xA434 => "LensModel",
        0xA435 => "LensSerialNumber",
        0xA460 => "CompositeImage",
        0xC4A5 => "PrintImageMatching",
        0xEA1C => "Padding",
        _ => return None,
    })
}
